[package]
name = "rust_cpal_examples"
version = "0.1.0"
authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2021"

[lib]
name = "synthlib"
path = "src/lib.rs"

[[bin]]
name  = "audio_device_info"
path = "src/audio_device_info/bin/main.rs"

[dependencies]
cpal = { version = "0.15.3" }
